name: Update README

on:
  schedule:
    - cron: '0 0 * * *'   # запускать каждый день
  workflow_dispatch:       

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats Card
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
